#this is like function but in Makefile it is target
say_hello:
#this is recipe
	@echo "Hello World"
#@ to supress echo as whole command and will print "Hello World" only
	
#syntax
#target: prerequisities
#<TAB>recipe
